import Link from 'next/link'
import { ArrowRight, Instagram, MessageCircle, ShoppingBag } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

export default async function Home(){
 const supabase=await createClient()
 const [{data:products},{data:settings}]=await Promise.all([
  supabase.from('products').select('id,name,price,badge,colors,image_urls').eq('is_active',true).order('created_at',{ascending:false}),
  supabase.from('store_settings').select('*').eq('id',true).single()
 ])
 const s=settings||{brand_name:'ZANK STUDIO',phone:'0798460604',instagram:'zankstudio',locations:'Algiers / Oran',announcement_text:'NEW DROP • PERSONALIZED TEES • COD AVAILABLE • DELIVERY ACROSS ALGERIA',announcement_enabled:true}
 return <main>
  {s.announcement_enabled&&<div className="topbar"><div className="marquee"><span>{s.announcement_text} • </span><span>{s.announcement_text} • </span></div></div>}
  <header className="header"><div className="container nav"><Link href="/" className="logo">{s.brand_name}</Link><nav className="navlinks"><a href="#shop">SHOP</a><a href="#custom">CUSTOM</a><a href="#delivery">DELIVERY</a></nav><Link className="iconbtn" href="/cart" aria-label="Cart"><ShoppingBag size={18}/></Link></div></header>
  <section className="hero"><div className="container hero-inner"><span className="kicker">{s.locations.toUpperCase()} · ALGERIA</span><h1>WEAR<br/>YOUR IDEA.</h1><p>Personalized tees made for people who would rather wear something with a point of view than another shirt nobody remembers.</p><a className="cta" href="#shop">SHOP THE DROP <ArrowRight size={15}/></a></div></section>
  <section className="section" id="shop"><div className="container"><div className="section-head"><div><p className="muted">01 / SHOP</p><h2>Latest pieces</h2></div><span className="muted">COD · DHD DELIVERY</span></div>{products?.length?<div className="grid">{products.map(p=><Link href={`/products/${p.id}`} className="card" key={p.id}><div className="product-image" style={p.image_urls?.[0]?{backgroundImage:`url(${p.image_urls[0]})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><span className="pill" style={{position:'absolute',top:12,left:12,zIndex:2}}>{p.badge||'NEW'}</span></div><div className="product-copy"><div className="product-name">{p.name}</div><div className="product-meta"><span className="muted">{(p.colors||[]).join(' / ')}</span><span className="price">{p.price.toLocaleString('fr-DZ')} DA</span></div></div></Link>)}</div>:<div className="empty">No products yet. Add your first drop from the admin.</div>}</div></section>
  <section className="section" id="custom" style={{background:'#050505',color:'#fff'}}><div className="container" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:60,alignItems:'center'}}><div><p style={{fontSize:11,fontWeight:900,letterSpacing:'.14em'}}>02 / YOUR DESIGN</p><h2 style={{fontSize:'clamp(45px,7vw,90px)',margin:'15px 0',letterSpacing:'-.07em'}}>MADE<br/>PERSONAL.</h2></div><div><p style={{color:'#aaa',lineHeight:1.8,fontSize:14}}>Choose your tee, size, color and personalisation. Orders are confirmed by phone or WhatsApp before production.</p><a className="cta" style={{background:'#fff',color:'#000'}} href="#shop">CHOOSE YOUR TEE <ArrowRight size={15}/></a></div></div></section>
  <section className="section" id="delivery"><div className="container"><div className="section-head"><div><p className="muted">03 / DELIVERY</p><h2>Built for Algeria.</h2></div></div><div className="split"><div className="panel" style={{padding:25}}><h3 style={{marginTop:0}}>DHD · HOME</h3><p className="muted" style={{lineHeight:1.7}}>Delivery across Algeria with pricing managed by Wilaya in the admin.</p></div><div className="panel" style={{padding:25}}><h3 style={{marginTop:0}}>DHD · STOP DESK</h3><p className="muted" style={{lineHeight:1.7}}>Choose stop-desk delivery when it suits you better. COD stays available.</p></div></div></div></section>
  <footer className="footer"><div className="container footer-grid"><div><div className="logo">{s.brand_name}</div><p className="muted">Personalized tees · {s.locations}</p></div><div style={{display:'flex',gap:10}}><a className="iconbtn" href={`https://instagram.com/${s.instagram}`} aria-label="Instagram"><Instagram size={17}/></a><a className="iconbtn" href="https://wa.me/213798460604" aria-label="WhatsApp"><MessageCircle size={17}/></a></div></div></footer>
 </main>
}
