'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'

type Item={id:string;product_id:string;name:string;price:number;color:string;size:string;quantity:number;image?:string;note?:string}
type Rate={home_price:number;stop_desk_price:number}
const wilayas=['Adrar','Chlef','Laghouat','Oum El Bouaghi','Batna','Béjaïa','Biskra','Béchar','Blida','Bouira','Tamanrasset','Tébessa','Tlemcen','Tiaret','Tizi Ouzou','Algiers','Djelfa','Jijel','Sétif','Saïda','Skikda','Sidi Bel Abbès','Annaba','Guelma','Constantine','Médéa','Mostaganem','M’Sila','Mascara','Ouargla','Oran','El Bayadh','Illizi','Bordj Bou Arréridj','Boumerdès','El Tarf','Tindouf','Tissemsilt','El Oued','Khenchela','Souk Ahras','Tipaza','Mila','Aïn Defla','Naâma','Aïn Témouchent','Ghardaïa','Relizane']

export default function Checkout(){
 const [items,setItems]=useState<Item[]>([]); const [wilaya,setWilaya]=useState('Algiers'); const [method,setMethod]=useState<'home'|'stop_desk'>('home'); const [rate,setRate]=useState<Rate|null>(null); const [done,setDone]=useState<number|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem('zank-cart')||'[]'))}catch{}},[])
 useEffect(()=>{fetch(`/api/delivery?wilaya=${encodeURIComponent(wilaya)}`).then(r=>r.ok?r.json():null).then(setRate).catch(()=>setRate(null))},[wilaya])
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.price*i.quantity,0),[items]); const delivery=rate?(method==='home'?rate.home_price:rate.stop_desk_price):0; const total=subtotal+delivery
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);const f=new FormData(e.currentTarget);const payload={customer_name:f.get('customer_name'),phone:f.get('phone'),email:f.get('email')||null,wilaya,commune:f.get('commune'),address:f.get('address'),delivery_method:method,items:items.map(i=>({product_id:i.product_id,quantity:i.quantity,color:i.color,size:i.size})),notes:f.get('notes')};const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();setLoading(false);if(!r.ok){setError(data.error||'Unable to place order.');return}localStorage.removeItem('zank-cart');setDone(data.order.order_number)}
 if(done) return <main><div className="container" style={{padding:'110px 0',maxWidth:650,textAlign:'center'}}><span className="kicker">ORDER #{done}</span><h1 style={{fontSize:'clamp(58px,10vw,110px)',letterSpacing:'-.08em',lineHeight:.88}}>THANK<br/>YOU.</h1><p className="muted" style={{lineHeight:1.8}}>Your COD order is recorded. We’ll confirm it by phone or WhatsApp on <strong>0798 46 06 04</strong>.</p><Link className="cta" href="/">BACK TO SHOP</Link></div></main>
 if(!items.length) return <main><div className="container" style={{padding:'110px 0'}}><div className="empty"><h2 style={{marginTop:0}}>Your bag is empty.</h2><Link className="cta" href="/#shop">SHOP THE DROP</Link></div></div></main>
 return <main><header className="header"><div className="container nav"><Link href="/" className="logo">ZANK STUDIO</Link></div></header><section className="section"><div className="container"><p className="muted">CHECKOUT / CASH ON DELIVERY</p><h1 style={{fontSize:'clamp(45px,7vw,90px)',letterSpacing:'-.07em',margin:'5px 0 30px'}}>PLACE ORDER.</h1><div className="checkout"><form className="panel" style={{padding:22}} onSubmit={submit}><div className="form"><div className="split"><div className="field"><label>Full name</label><input name="customer_name" required placeholder="Your name"/></div><div className="field"><label>Phone</label><input name="phone" required inputMode="tel" placeholder="07 XX XX XX XX"/></div></div><div className="field"><label>Email (optional)</label><input name="email" type="email" placeholder="you@example.com"/></div><div className="field"><label>Wilaya</label><select value={wilaya} onChange={e=>setWilaya(e.target.value)}>{wilayas.map(w=><option key={w}>{w}</option>)}</select></div><div className="field"><label>Commune</label><input name="commune" required placeholder="Commune"/></div><div className="field"><label>Delivery</label><div className="split"><button type="button" className={method==='home'?'btn-black':'btn-white'} onClick={()=>setMethod('home')}>DHD HOME {rate?`· ${rate.home_price.toLocaleString('fr-DZ')} DA`:''}</button><button type="button" className={method==='stop_desk'?'btn-black':'btn-white'} onClick={()=>setMethod('stop_desk')}>STOP DESK {rate?`· ${rate.stop_desk_price.toLocaleString('fr-DZ')} DA`:''}</button></div></div><div className="field"><label>Address / Stop desk details</label><textarea name="address" required rows={4} placeholder={method==='home'?'Street, building, apartment…':'Preferred DHD stop desk / details…'}/></div><div className="field"><label>Order note</label><textarea name="notes" rows={3} placeholder="Optional note…"/></div>{error&&<p style={{color:'#b00020',fontSize:12}}>{error}</p>}<div className="panel" style={{padding:16,background:'#fafafa'}}><strong>CASH ON DELIVERY</strong><p className="muted" style={{marginBottom:0}}>No online payment. We confirm before dispatch.</p></div><button className="btn-black" type="submit" disabled={loading||!rate}>{loading?'PLACING ORDER…':`CONFIRM COD ORDER · ${total.toLocaleString('fr-DZ')} DA`}</button></div></form><div className="panel summary"><h3 style={{marginTop:0}}>ORDER SUMMARY</h3>{items.map(i=><div className="summary-row" key={i.id}><span>{i.name} × {i.quantity}<br/><small className="muted">{i.color} / {i.size}</small></span><strong>{(i.price*i.quantity).toLocaleString('fr-DZ')} DA</strong></div>)}<div className="summary-row"><span>Delivery</span><strong>{delivery.toLocaleString('fr-DZ')} DA</strong></div><div className="summary-row" style={{fontSize:17,borderBottom:0}}><strong>TOTAL COD</strong><strong>{total.toLocaleString('fr-DZ')} DA</strong></div></div></div></div></section></main>
}
