"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

const wilayas = ["Adrar","Chlef","Laghouat","Oum El Bouaghi","Batna","Béjaïa","Biskra","Béchar","Blida","Bouira","Tamanrasset","Tébessa","Tlemcen","Tiaret","Tizi Ouzou","Algiers","Djelfa","Jijel","Sétif","Saïda","Skikda","Sidi Bel Abbès","Annaba","Guelma","Constantine","Médéa","Mostaganem","M’Sila","Mascara","Ouargla","Oran","El Bayadh","Illizi","Bordj Bou Arréridj","Boumerdès","El Tarf","Tindouf","Tissemsilt","El Oued","Khenchela","Souk Ahras","Tipaza","Mila","Aïn Defla","Naâma","Aïn Témouchent","Ghardaïa","Relizane"];

export default function Checkout(){
 const [wilaya,setWilaya]=useState("Algiers"); const [method,setMethod]=useState("home"); const [submitted,setSubmitted]=useState(false);
 const delivery=useMemo(()=>method==='home'?700:500,[method]); const subtotal=3500; const total=subtotal+delivery;
 if(submitted) return <main><div className="container" style={{padding:'110px 0',maxWidth:650,textAlign:'center'}}><span className="kicker">ORDER RECEIVED</span><h1 style={{fontSize:70,letterSpacing:'-.07em',lineHeight:.9}}>THANK<br/>YOU.</h1><p className="muted" style={{lineHeight:1.8}}>Your COD order has been recorded. We’ll confirm it by phone or WhatsApp on <strong>0798 46 06 04</strong>.</p><Link className="cta" href="/">BACK TO SHOP</Link></div></main>;
 return <main><header className="header"><div className="container nav"><Link href="/" className="logo">ZANK STUDIO</Link></div></header><section className="section"><div className="container"><p className="muted">CHECKOUT / CASH ON DELIVERY</p><h1 style={{fontSize:'clamp(45px,7vw,90px)',letterSpacing:'-.07em',margin:'5px 0 30px'}}>PLACE ORDER.</h1><div className="checkout"><form className="panel" style={{padding:22}} onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><div className="form"><div className="split"><div className="field"><label>Full name</label><input required placeholder="Your name"/></div><div className="field"><label>Phone</label><input required inputMode="tel" placeholder="0 7 XX XX XX XX"/></div></div><div className="field"><label>Wilaya</label><select value={wilaya} onChange={e=>setWilaya(e.target.value)}>{wilayas.map(w=><option key={w}>{w}</option>)}</select></div><div className="field"><label>Commune</label><input required placeholder="Commune"/></div><div className="field"><label>Delivery method</label><div className="split"><button type="button" className={method==='home'?'btn-black':'btn-white'} onClick={()=>setMethod('home')}>DHD HOME</button><button type="button" className={method==='desk'?'btn-black':'btn-white'} onClick={()=>setMethod('desk')}>DHD STOP DESK</button></div></div><div className="field"><label>Address / Stop desk details</label><textarea required rows={4} placeholder={method==='home'?'Street, building, apartment...':'Nearest DHD stop desk / details...'}/></div><div className="panel" style={{padding:16,background:'#fafafa'}}><strong>CASH ON DELIVERY</strong><p className="muted" style={{marginBottom:0}}>No payment is taken online. We confirm the order before dispatch.</p></div><button className="btn-black" type="submit">CONFIRM COD ORDER · {total.toLocaleString('fr-DZ')} DA</button></div></form><div className="panel summary"><h3 style={{marginTop:0}}>SUMMARY</h3><div className="summary-row"><span>Custom Tee 01 × 1</span><strong>3,500 DA</strong></div><div className="summary-row"><span>{method==='home'?'DHD Home':'DHD Stop Desk'} · {wilaya}</span><strong>{delivery.toLocaleString('fr-DZ')} DA</strong></div><div className="summary-row" style={{fontSize:17,borderBottom:0}}><strong>TOTAL COD</strong><strong>{total.toLocaleString('fr-DZ')} DA</strong></div></div></div></div></section></main>;
}
